/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vue;

import DAO.FilmDAO;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import static javax.management.remote.JMXConnectorFactory.connect;
import javax.swing.*;
import jdbc2020.*;
import DAO.*;

/**
 *
 * @author user
 */
public class GestiondeSeance extends javax.swing.JFrame {

    private SeanceDAO seance;
    private String maRequete;
    private int count = 0;
    private FilmDAO film;
    public int nbSalle = 10;
    public Connexion connection;

    DefaultListModel<String> listModelTitre = new DefaultListModel<>();
    DefaultListModel<String> listModelInfoSeance = new DefaultListModel<>();
    DefaultListModel<String> listModelRech = new DefaultListModel<>();

    /**
     * Creates new form GestiondeSeance
     *
     * @throws java.sql.SQLException
     * @throws java.lang.ClassNotFoundException
     */
    public GestiondeSeance() throws SQLException, ClassNotFoundException {
        super("Gestion des seances");
        initComponents();

        //desactivation btn de suppression
        BtnSupprimer.setEnabled(false);
        BtnAjouter.setEnabled(false);
        //Creation JList
        seance = new SeanceDAO("cinema", "root", "");
        listModelRech = seance.getDateHeureFilm();
        ListeSeance.setModel(affichage(listModelRech));

        //Creation de la combo box des films
        film = new FilmDAO("cinema", "root", "");
        listModelTitre = film.getFilmTitre();
        for (int i = 0; i < listModelTitre.size(); i++) {
            NomFilm.addItem(listModelTitre.get(i));
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        BtnRecherche = new javax.swing.JButton();
        BtnReset = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        BtnAjouter = new javax.swing.JButton();
        BtnSupprimer = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListeSeance = new javax.swing.JList<>();
        HeureDebut = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        NomFilm = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        DateSeance = new javax.swing.JFormattedTextField();
        RechercheSeance = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        SalleProjection = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(168, 26, 3));
        jPanel1.setLayout(null);

        BtnRecherche.setText("Recherche");
        BtnRecherche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRechercheActionPerformed(evt);
            }
        });
        jPanel1.add(BtnRecherche);
        BtnRecherche.setBounds(740, 60, 100, 40);

        BtnReset.setText("Reset");
        BtnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnResetActionPerformed(evt);
            }
        });
        jPanel1.add(BtnReset);
        BtnReset.setBounds(850, 60, 70, 40);

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel1.setText("Gestion des Seances");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(98, 30, 178, 41);

        BtnAjouter.setText("AJOUTER");
        BtnAjouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAjouterActionPerformed(evt);
            }
        });
        jPanel1.add(BtnAjouter);
        BtnAjouter.setBounds(70, 340, 132, 50);

        BtnSupprimer.setText("SUPPRIMER");
        BtnSupprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSupprimerActionPerformed(evt);
            }
        });
        jPanel1.add(BtnSupprimer);
        BtnSupprimer.setBounds(240, 340, 137, 50);

        ListeSeance.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ListeSeanceMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(ListeSeance);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(450, 120, 470, 300);

        try {
            HeureDebut.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        HeureDebut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                HeureDebutMouseExited(evt);
            }
        });
        jPanel1.add(HeureDebut);
        HeureDebut.setBounds(48, 252, 132, 40);

        jLabel2.setText("Heure de la séance : ");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(48, 231, 103, 15);

        jPanel1.add(NomFilm);
        NomFilm.setBounds(206, 158, 226, 40);

        jLabel3.setText("Date de la séance :");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(50, 140, 100, 15);

        try {
            DateSeance.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-##-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        DateSeance.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                DateSeanceMouseExited(evt);
            }
        });
        jPanel1.add(DateSeance);
        DateSeance.setBounds(50, 160, 130, 40);

        try {
            RechercheSeance.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-##-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel1.add(RechercheSeance);
        RechercheSeance.setBounds(450, 60, 280, 40);

        jLabel4.setText("Recherche selon la date :");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(450, 40, 150, 15);

        SalleProjection.setModel(new javax.swing.SpinnerNumberModel(1, 1, 10, 1));
        jPanel1.add(SalleProjection);
        SalleProjection.setBounds(370, 250, 60, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 938, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 436, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Supression de seances
     * @param evt 
     */
    private void BtnSupprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSupprimerActionPerformed
        // TODO add your handling code here:
        int index = ListeSeance.getSelectedIndex();//Capture de l'element selectionne
        //Creer et execute la requete sql pour obtenir les 
        DefaultListModel<String> eltRech = new DefaultListModel<>();
        String textAffich = "Voulez vous supprimer cette seance ?\n" + listModelRech.get(index + 2) + ", " + listModelRech.get(index) + ", " + listModelRech.get(index + 1);
        int result = JOptionPane.showConfirmDialog(null, textAffich, "Suppression", JOptionPane.YES_NO_OPTION);

        if (result == JOptionPane.YES_OPTION) {
            listModelRech.removeElementAt(index);
            try {
                seance.delSeanceByFilmDateHeure(Integer.parseInt(film.getIDByTitre(listModelRech.get(index + 1))), listModelRech.get(index + 2), listModelRech.get(index));
            } catch (SQLException | ClassNotFoundException ex) {
                Logger.getLogger(GestiondeSeance.class.getName()).log(Level.SEVERE, null, ex);
            }
            JOptionPane.showMessageDialog(null, "Seance Supprimée");
        } else {

        }
    }//GEN-LAST:event_BtnSupprimerActionPerformed
    /**
     * Ajouter une seance
     * @param evt 
     */
    private void BtnAjouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAjouterActionPerformed
        if ((DateSeance.getText().equals("    -  -  ")) || (NomFilm.getSelectedItem() == null) || (HeureDebut.getText().equals("  :  :  ")) || (SalleProjection.getValue() == null)) {
            JOptionPane.showMessageDialog(null, "Veuillez completer tout les champs");
        } else {
            //String maRequete = "INSERT INTO seance(heureDebut,ID_Film,salle,Date) VALUES('" + HeureDebut.getText() + "'," + NomFilm.getSelectedItem() + "," + SalleProjection.getValue() + ",'" + DateSeance.getText()+ "'" ;           
            try {
                seance.addSeance((int) SalleProjection.getValue(), Integer.parseInt(film.getIDByTitre((String) NomFilm.getSelectedItem())), DateSeance.getText(), HeureDebut.getText());
            } catch (SQLException | ClassNotFoundException ex) {
                Logger.getLogger(GestiondeSeance.class.getName()).log(Level.SEVERE, null, ex);
            }
            listModelRech.addElement(DateSeance.getText());
            JOptionPane.showMessageDialog(null, "La seance a ete ajoute");
        }
    }//GEN-LAST:event_BtnAjouterActionPerformed
    /**
     * /**
     * //Recherche de seance
     * @param evt 
     */
    private void BtnRechercheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRechercheActionPerformed
        if ((RechercheSeance.getText().equals("")) || (DateSeance.getText().equals("Recherche de la seance"))) {
            JOptionPane.showMessageDialog(null, "Veuillez rentrer une date à chercher");
        } else {
            try {
                listModelRech = seance.getDateHeureFilmByDate(RechercheSeance.getText());
            } catch (SQLException ex) {
                Logger.getLogger(PageSuppression.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(GestiondeSeance.class.getName()).log(Level.SEVERE, null, ex);
            }

            ListeSeance.setModel(affichage(listModelRech));
            //ListeSeance.setModel(listModelInfoSeance);
            //RechercheSeance.setText("Recherche de la seance ");
        }
    }//GEN-LAST:event_BtnRechercheActionPerformed
    /**
     * Annulation de la dernière action
     * @param evt 
     */
    private void BtnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnResetActionPerformed
        try {
            listModelRech = seance.getDateHeureFilm();
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(GestiondeSeance.class.getName()).log(Level.SEVERE, null, ex);
        }
        RechercheSeance.setText(null);
        ListeSeance.setModel(affichage(listModelRech));

    }//GEN-LAST:event_BtnResetActionPerformed

    private void ListeSeanceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ListeSeanceMouseClicked
        if (ListeSeance.getSelectedIndex() > -1) {
            BtnSupprimer.setEnabled(true);
        }
    }//GEN-LAST:event_ListeSeanceMouseClicked

    private void DateSeanceMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DateSeanceMouseExited
        if (((DateSeance.getText().equals("    -  -  ") || NomFilm.getSelectedItem() == null) || HeureDebut.getText().equals("  :  :  ")) || SalleProjection.getValue() == null) {
            BtnAjouter.setEnabled(false);
        } else {
            BtnAjouter.setEnabled(true);
        }
    }//GEN-LAST:event_DateSeanceMouseExited

    private void HeureDebutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HeureDebutMouseExited
        if (((DateSeance.getText().equals("    -  -  ") || NomFilm.getSelectedItem() == null) || HeureDebut.getText().equals("  :  :  ")) || SalleProjection.getValue() == null) {
            BtnAjouter.setEnabled(false);
        } else {
            BtnAjouter.setEnabled(true);
        }
    }//GEN-LAST:event_HeureDebutMouseExited

    private DefaultListModel<String> affichage(DefaultListModel<String> listModel) {
        DefaultListModel<String> list = new DefaultListModel<>();
        for (int i = 0; i < listModel.size(); i += 3) {
            list.add(i / 3, listModel.get(i + 2) + ", " + listModel.get(i) + ", " + listModel.get(i + 1));
        }
        return list;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAjouter;
    private javax.swing.JButton BtnRecherche;
    private javax.swing.JButton BtnReset;
    private javax.swing.JButton BtnSupprimer;
    private javax.swing.JFormattedTextField DateSeance;
    private javax.swing.JFormattedTextField HeureDebut;
    private javax.swing.JList<String> ListeSeance;
    private javax.swing.JComboBox<String> NomFilm;
    private javax.swing.JFormattedTextField RechercheSeance;
    private javax.swing.JSpinner SalleProjection;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
