/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vue;

import java.awt.event.*;
import java.awt.*;
import java.util.*;
import javax.swing.*;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import jdbc2020.*;

/**
 *
 * @author pierr
 */
public class PageSuppression extends javax.swing.JFrame {

    public Connexion connect;
    private String requete;

    DefaultListModel<String> listModel = new DefaultListModel<>();
    
    public PageSuppression() throws SQLException, ClassNotFoundException {
        initComponents();
        
        btnDel.setEnabled(false);
        //BtnAdd.setEnabled(true);

        //Connection a la bdd
        connect = new Connexion("Cinema", "root", "");
        requete = "SELECT titre FROM film";
        listModel = connect.requestDemande(requete);
        listTitreFilm.setModel(listModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listTitreFilm = new javax.swing.JList<>();
        btnAdd = new javax.swing.JButton();
        btnDel = new javax.swing.JButton();
        Titre = new javax.swing.JTextField();
        PrenomReal = new javax.swing.JTextField();
        NomReal = new javax.swing.JTextField();
        Duree = new javax.swing.JTextField();
        Genre = new javax.swing.JTextField();
        Note = new javax.swing.JTextField();
        Synopsis = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        Recherche = new javax.swing.JTextField();
        btnReset = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        listTitreFilm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listTitreFilmMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(listTitreFilm);

        btnAdd.setText("AJOUTER");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnDel.setText("SUPPRIMER");
        btnDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelActionPerformed(evt);
            }
        });

        Titre.setText("Titre");
        Titre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TitreMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                TitreMouseExited(evt);
            }
        });

        PrenomReal.setText("PrenomReal");
        PrenomReal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PrenomRealMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PrenomRealMouseExited(evt);
            }
        });

        NomReal.setText("NomReal");
        NomReal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NomRealMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                NomRealMouseExited(evt);
            }
        });

        Duree.setText("Duree");
        Duree.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DureeMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                DureeMouseExited(evt);
            }
        });

        Genre.setText("Genre");
        Genre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GenreMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                GenreMouseExited(evt);
            }
        });

        Note.setText("Note");
        Note.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NoteMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                NoteMouseExited(evt);
            }
        });

        Synopsis.setText("Synopsis");
        Synopsis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SynopsisMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SynopsisMouseExited(evt);
            }
        });

        jButton2.setText("Recheche");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        Recherche.setText("Recherche");
        Recherche.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RechercheMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                RechercheMouseExited(evt);
            }
        });

        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 14, Short.MAX_VALUE)
                        .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnDel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Duree, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(60, 60, 60)
                                .addComponent(Genre, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Note))
                            .addComponent(Titre)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(PrenomReal, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(NomReal))
                            .addComponent(Synopsis))
                        .addGap(18, 18, 18)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Recherche, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnReset))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Recherche)
                    .addComponent(btnReset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Titre, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 1, Short.MAX_VALUE))
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(PrenomReal, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                            .addComponent(NomReal))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Duree, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                            .addComponent(Note)
                            .addComponent(Genre))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Synopsis, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnDel, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelActionPerformed
        String SelectedTitle = (String) listTitreFilm.getSelectedValue();//Capture de l'element selectionne
        int index = listTitreFilm.getSelectedIndex();
        //Creer et execute la requete sql pour obtenir les 
        String requeteInfo = "SELECT NomRealisateur, PrenomRealisateur FROM film WHERE titre LIKE '" + SelectedTitle + "'";
        DefaultListModel<String> eltRech = new DefaultListModel<>();
        try {
            eltRech = connect.requestDemande(requeteInfo);
        } catch (SQLException ex) {
            Logger.getLogger(SuppressionTest.class.getName()).log(Level.SEVERE, null, ex);
        }

        String textAffich = "Voulez vous supprimer ce film ?\n" + SelectedTitle + "\n" + eltRech.get(1) + ", " + eltRech.get(0);
        int result = JOptionPane.showConfirmDialog(null, textAffich, "Suppression", JOptionPane.YES_NO_OPTION);
        
        if(result == JOptionPane.YES_OPTION){
            listModel.removeElementAt(index);
            String requeteSuppr = "DELETE FROM Film WHERE Titre LIKE '" + SelectedTitle + "' AND Nomrealisateur LIKE '" + eltRech.get(1) + "'";
            try {
                connect.executeUpdate(requeteSuppr);
            } catch (SQLException ex) {
                Logger.getLogger(SuppressionTest.class.getName()).log(Level.SEVERE, null, ex);
            }
            JOptionPane.showMessageDialog(null, "Film Supprime");
        }
        else{
            
        }
    }//GEN-LAST:event_btnDelActionPerformed

    private void listTitreFilmMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listTitreFilmMouseClicked
        if (listTitreFilm.getSelectedIndex() > -1) {
            btnDel.setEnabled(true);
            //BtnAdd.setEnabled(false);
        }
    }//GEN-LAST:event_listTitreFilmMouseClicked

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        if((Titre.getText().equals(""))||(Titre.getText().equals("Titre"))||(PrenomReal.getText().equals(""))||(PrenomReal.getText().equals("PrenomReal"))||(NomReal.getText().equals(""))||(NomReal.getText().equals("NomReal"))||(Duree.getText().equals(""))||(Duree.getText().equals("Duree"))||(Note.getText().equals(""))||(Note.getText().equals("Note"))||(Genre.getText().equals(""))||(Genre.getText().equals("Genre"))||(Synopsis.getText().equals(""))||(Synopsis.getText().equals("Synopsis"))){
            JOptionPane.showMessageDialog(null, "Veuillez completer tout les champs");
        }
        else{
            String requete="INSERT INTO film(Titre,NomRealisateur,PrenomRealisateur,duree,genre,note,synopsis) VALUES('"+Titre.getText()+"','"+NomReal.getText()+"','"+PrenomReal.getText()+"','"+Duree.getText()+"','"+Genre.getText()+"','"+Note.getText()+"','"+Synopsis.getText()+"'"+")";
            System.out.println(requete);
            try {
                connect.executeUpdate(requete);
            } catch (SQLException ex) {
                Logger.getLogger(PageSuppression.class.getName()).log(Level.SEVERE, null, ex);
            }
            listModel.addElement(Titre.getText());
            JOptionPane.showMessageDialog(null, "Le film a ete ajoute");
            Titre.setText("Titre");
            PrenomReal.setText("Prenomreal");
            NomReal.setText("NomReal");
            Duree.setText("Duree");
            Genre.setText("Genre");
            Note.setText("Note");
            Synopsis.setText("Synopsis");
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void TitreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TitreMouseClicked
        Titre.setText(null);
    }//GEN-LAST:event_TitreMouseClicked

    private void PrenomRealMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PrenomRealMouseClicked
        PrenomReal.setText(null);
    }//GEN-LAST:event_PrenomRealMouseClicked

    private void NomRealMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NomRealMouseClicked
        NomReal.setText(null);
    }//GEN-LAST:event_NomRealMouseClicked

    private void DureeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DureeMouseClicked
        Duree.setText(null);
    }//GEN-LAST:event_DureeMouseClicked

    private void GenreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GenreMouseClicked
        Genre.setText(null);
    }//GEN-LAST:event_GenreMouseClicked

    private void NoteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NoteMouseClicked
        Note.setText(null);
    }//GEN-LAST:event_NoteMouseClicked

    private void SynopsisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SynopsisMouseClicked
        Synopsis.setText(null);
    }//GEN-LAST:event_SynopsisMouseClicked

    private void TitreMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TitreMouseExited
        if(Titre.getText().equals("")){
            Titre.setText("Titre");
        }
    }//GEN-LAST:event_TitreMouseExited

    private void PrenomRealMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PrenomRealMouseExited
        if(PrenomReal.getText().equals("")){
            PrenomReal.setText("PrenomReal");
        }
    }//GEN-LAST:event_PrenomRealMouseExited

    private void NomRealMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NomRealMouseExited
        if(NomReal.getText().equals("")){
            NomReal.setText("NomReal");
        }
    }//GEN-LAST:event_NomRealMouseExited

    private void DureeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DureeMouseExited
        if(Duree.getText().equals("")){
            Duree.setText("Duree");
        }
    }//GEN-LAST:event_DureeMouseExited

    private void GenreMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GenreMouseExited
        if(Genre.getText().equals("")){
            Genre.setText("Genre");
        }
    }//GEN-LAST:event_GenreMouseExited

    private void NoteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NoteMouseExited
        if(Note.getText().equals("")){
            Note.setText("Note");
        }
    }//GEN-LAST:event_NoteMouseExited

    private void SynopsisMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SynopsisMouseExited
        if(Synopsis.getText().equals("")){
            Synopsis.setText("Synopsis");
        }
    }//GEN-LAST:event_SynopsisMouseExited

    private void RechercheMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RechercheMouseClicked
        Recherche.setText(null);
    }//GEN-LAST:event_RechercheMouseClicked

    private void RechercheMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RechercheMouseExited
        if(Recherche.getText().equals("")){
            Recherche.setText("Recherche");
        }
    }//GEN-LAST:event_RechercheMouseExited

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if((Recherche.getText().equals(""))||(PrenomReal.getText().equals("Recherche"))){
            JOptionPane.showMessageDialog(null, "Veuillez rentrer un titre à chercher");
        }
        else{
            String requete = "SELECT titre FROM Film WHERE titre LIKE '%"+Recherche.getText()+"%'";
            try {
                listModel = connect.requestDemande(requete);
            } catch (SQLException ex) {
                Logger.getLogger(PageSuppression.class.getName()).log(Level.SEVERE, null, ex);
            }
            listTitreFilm.setModel(listModel);
            Recherche.setText("Recherche");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        requete = "SELECT titre FROM film";
        try {
            listModel = connect.requestDemande(requete);
        } catch (SQLException ex) {
            Logger.getLogger(PageSuppression.class.getName()).log(Level.SEVERE, null, ex);
        }
        listTitreFilm.setModel(listModel);
    }//GEN-LAST:event_btnResetActionPerformed
  
    /**
     * @param args the command line arguments
    *//*
    public static void main(String args[]) {
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new PageSuppression().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(PageSuppression.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(PageSuppression.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Duree;
    private javax.swing.JTextField Genre;
    private javax.swing.JTextField NomReal;
    private javax.swing.JTextField Note;
    private javax.swing.JTextField PrenomReal;
    private javax.swing.JTextField Recherche;
    private javax.swing.JTextField Synopsis;
    private javax.swing.JTextField Titre;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDel;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> listTitreFilm;
    // End of variables declaration//GEN-END:variables
}
