/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vue;

import java.awt.event.*;
import java.awt.*;
import java.util.*;
import javax.swing.*;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import jdbc2020.*;
import DAO.*;

/**
 *
 * @author pierr
 */
public class PageConnexion extends javax.swing.JFrame {

    private ClientDAO client;
    private EmployeDAO employe;
    private String requeteClient, requeteEmploye;
    private String email, NomEmploye;
    private boolean isEmploye = true;
    public boolean connexionValid = false;
    public boolean EmpCo;
    PageAccueil pa;

    public PageConnexion() throws SQLException, ClassNotFoundException {
        super("Connexion");
        initComponents();
        //connexion a la bdd
        employe = new EmployeDAO("cinema", "root", "");
        client = new ClientDAO("cinema", "root", "");
        //Initialisation Panel
        PanelClient.setVisible(true);
        PanelEmploye.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        PanelClient = new javax.swing.JPanel();
        lblEmail = new javax.swing.JLabel();
        Email = new javax.swing.JTextField();
        PanelEmploye = new javax.swing.JPanel();
        lblIdentifiant = new javax.swing.JLabel();
        Identifiant = new javax.swing.JTextField();
        PanelCommun = new javax.swing.JPanel();
        MotDePasse = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        btnCo = new javax.swing.JButton();
        chechEmp = new javax.swing.JCheckBox();
        btnInscription = new javax.swing.JButton();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(168, 26, 3));
        setBounds(new java.awt.Rectangle(800, 350, 0, 0));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });
        getContentPane().setLayout(null);

        jLayeredPane1.setBackground(new java.awt.Color(168, 26, 3));

        PanelClient.setBackground(new java.awt.Color(168, 26, 3));
        PanelClient.setLayout(null);

        lblEmail.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lblEmail.setText(" Email :");
        PanelClient.add(lblEmail);
        lblEmail.setBounds(10, 20, 60, 19);

        Email.setBackground(new java.awt.Color(0, 0, 0));
        Email.setForeground(new java.awt.Color(255, 255, 255));
        Email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmailActionPerformed(evt);
            }
        });
        PanelClient.add(Email);
        Email.setBounds(12, 42, 280, 40);

        PanelEmploye.setBackground(new java.awt.Color(168, 26, 3));
        PanelEmploye.setLayout(null);

        lblIdentifiant.setBackground(new java.awt.Color(0, 0, 0));
        lblIdentifiant.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lblIdentifiant.setText("Identifiant :");
        PanelEmploye.add(lblIdentifiant);
        lblIdentifiant.setBounds(12, 21, 80, 19);

        Identifiant.setBackground(new java.awt.Color(0, 0, 0));
        Identifiant.setForeground(new java.awt.Color(255, 255, 255));
        Identifiant.setMaximumSize(new java.awt.Dimension(4, 19));
        PanelEmploye.add(Identifiant);
        Identifiant.setBounds(10, 40, 274, 40);

        jLayeredPane1.setLayer(PanelClient, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(PanelEmploye, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelClient, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(PanelEmploye, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addComponent(PanelClient, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(PanelEmploye, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE))
        );

        getContentPane().add(jLayeredPane1);
        jLayeredPane1.setBounds(0, 0, 300, 90);

        PanelCommun.setBackground(new java.awt.Color(168, 26, 3));

        MotDePasse.setBackground(new java.awt.Color(0, 0, 0));
        MotDePasse.setForeground(new java.awt.Color(255, 255, 255));
        MotDePasse.setMaximumSize(new java.awt.Dimension(4, 19));

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel2.setText("Mot de passe :");

        btnCo.setBackground(new java.awt.Color(0, 0, 0));
        btnCo.setForeground(new java.awt.Color(168, 26, 3));
        btnCo.setText("Connexion");
        btnCo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCoActionPerformed(evt);
            }
        });

        chechEmp.setBackground(new java.awt.Color(168, 26, 3));
        chechEmp.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        chechEmp.setText("Employé");
        chechEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chechEmpActionPerformed(evt);
            }
        });

        btnInscription.setBackground(new java.awt.Color(0, 0, 0));
        btnInscription.setForeground(new java.awt.Color(168, 26, 3));
        btnInscription.setText("Inscription");
        btnInscription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInscriptionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelCommunLayout = new javax.swing.GroupLayout(PanelCommun);
        PanelCommun.setLayout(PanelCommunLayout);
        PanelCommunLayout.setHorizontalGroup(
            PanelCommunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelCommunLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelCommunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelCommunLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelCommunLayout.createSequentialGroup()
                        .addGroup(PanelCommunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(PanelCommunLayout.createSequentialGroup()
                                .addComponent(btnCo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 112, Short.MAX_VALUE)
                                .addComponent(chechEmp))
                            .addComponent(MotDePasse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
            .addGroup(PanelCommunLayout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(btnInscription)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        PanelCommunLayout.setVerticalGroup(
            PanelCommunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelCommunLayout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MotDePasse, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(PanelCommunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCo)
                    .addComponent(chechEmp))
                .addGap(18, 18, 18)
                .addComponent(btnInscription)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(PanelCommun);
        PanelCommun.setBounds(0, 90, 300, 170);
        getContentPane().add(Background);
        Background.setBounds(0, 0, 30, 30);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void EmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmailActionPerformed
    /**
     * on verifie que les champs sont remplis si oui, on verifie que le mdp
     * correspond au nom(employe) ou a l email(client) si c est le cas, on ouvre
     * une nouvelle page d accueil personnalisee en fonction du type du compte
     *
     * @param evt
     */
    private void btnCoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCoActionPerformed
        //cas d'un employé
        //on verifie que les champs sont remplis
        if (!isEmploye) {
            if ((Identifiant.getText().equals("")) || (MotDePasse.getText().equals(""))) {
                JOptionPane.showMessageDialog(null, "Veuillez remplir tous les champs");
            } else {
                //on verifie que le mdp correspond au nom de l'employe
                try {
                    employe = new EmployeDAO("cinema", "root", "");
                    // si oui, nouvelle page d'accueil personalisée pour l'employé
                    if ((employe.getLoginByNom(Identifiant.getText())).equals(MotDePasse.getText())) {
                        JOptionPane.showMessageDialog(null, "Connexion");
                        connexionValid = true;
                        EmpCo = true;
                        this.dispose();
                        pa = new PageAccueil(connexionValid, EmpCo);
                        pa.setVisible(true);
                        //sinon, message d'erreur et on recommence
                    } else {
                        JOptionPane.showMessageDialog(null, "Mot de passe erroné");
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(PageConnexion.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ArrayIndexOutOfBoundsException e) {
                    JOptionPane.showMessageDialog(null, "Identifiant inconnu");
                    Identifiant.setText(null);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(PageConnexion.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            //cas d'un client
            //on verifie que les champs sont remplis
        } else {
            if ((Email.getText().equals("")) || (MotDePasse.getText().equals(""))) {
                JOptionPane.showMessageDialog(null, "Veuillez remplir tous les champs");
            } else {
                //on verifie que le mdp correspond a l'email du client
                try {
                    // si oui, nouvelle page d'accueil personalisée pour le client
                    if ((client.getLoginByEmail(Email.getText())).equals(MotDePasse.getText())) {
                        JOptionPane.showMessageDialog(null, "Connexion");
                        connexionValid = true;
                        EmpCo = false;
                        this.dispose();
                        pa = new PageAccueil(true, false);
                        pa.setVisible(true);
                        pa.client = Integer.parseInt((String) (client.getIDByMail(Email.getText())));
                        //sinon, message d'erreur et on recommence
                    } else {
                        JOptionPane.showMessageDialog(null, "Mot de passe erroné");
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(PageConnexion.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ArrayIndexOutOfBoundsException e) {
                    JOptionPane.showMessageDialog(null, "Identifiant inconnu");
                    Email.setText(null);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(PageConnexion.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }//GEN-LAST:event_btnCoActionPerformed
    /**
     * si on choisit d'être un employé, les champs de connexion client, sont
     * remplacés par ceux de employés
     *
     * @param evt
     */
    private void chechEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chechEmpActionPerformed

        if (isEmploye) {
            PanelEmploye.setVisible(true);
            PanelClient.setVisible(false);
        } else {
            PanelEmploye.setVisible(false);
            PanelClient.setVisible(true);
        }
        isEmploye = !isEmploye;
    }//GEN-LAST:event_chechEmpActionPerformed
    /**
     * si on appuie sur le bouton d'inscription, on ouvre une page d'inscription
     * et on ferme celle-ci
     *
     * @param evt
     */
    private void btnInscriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInscriptionActionPerformed

        JOptionPane.showMessageDialog(null, "Vous allez être redirige vers la page d'inscription");
        this.dispose();
        try {
            PageInscription p = new PageInscription();
            p.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(PageConnexion.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(PageConnexion.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnInscriptionActionPerformed
    /**
     * si on ferme la page,ça ouvre une page d'accueil avec l'accès d'un employé
     *
     * @param evt
     */
    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed

        try {
            if (!connexionValid) {
                PageAccueil pa = new PageAccueil(connexionValid, EmpCo);
                pa.setVisible(true);
            }
        } catch (SQLException ex) {
            Logger.getLogger(PageConnexion.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(PageConnexion.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formWindowClosed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PageConnexion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PageConnexion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PageConnexion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PageConnexion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new PageConnexion().setVisible(true);
                } catch (SQLException | ClassNotFoundException ex) {
                    Logger.getLogger(PageConnexion.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JTextField Email;
    private javax.swing.JTextField Identifiant;
    private javax.swing.JPasswordField MotDePasse;
    private javax.swing.JPanel PanelClient;
    private javax.swing.JPanel PanelCommun;
    private javax.swing.JPanel PanelEmploye;
    private javax.swing.JButton btnCo;
    private javax.swing.JButton btnInscription;
    private javax.swing.JCheckBox chechEmp;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblIdentifiant;
    // End of variables declaration//GEN-END:variables
}
