/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vue;

import DAO.*;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.time.*;
import java.time.format.DateTimeFormatter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.io.*;
import java.text.ParseException;
import javax.swing.*;
import jdbc2020.Connexion;
import java.util.*;
import java.text.SimpleDateFormat;

/**
 *
 * @author pierr
 */
public class PagePayement extends javax.swing.JFrame {

    //Initialisation DAO
    private BilletDAO billet;
    private SeanceDAO seance;
    private FilmDAO film;

    //Import des variables
    private final boolean connexionValid;
    private boolean Emp;
    int nbVenduSernior, nbVenduMembre, nbVenduEnfant, nbVenduPasCo, id_film, id_client, id_seance;

    //Variables utiles uniquement dans ce programme
    boolean PayOK = false;
    private String sdate;
    private int countCrypto = 0;
    private int countNum = 0;

    /**
     * Creates new form PagePayement
     *
     * @param connexionValid
     */
    public PagePayement(boolean connexionValid, int nbMembre, int nbSenior, int nbEnfant, int nbPasCo, int film, int seance, int client) {
        super("Page De Payement");
        initComponents();
        //recuperation de la valeur de chacun des attributs
        this.connexionValid = connexionValid;
        nbVenduSernior = nbSenior;
        nbVenduMembre = nbMembre;
        nbVenduEnfant = nbEnfant;
        nbVenduPasCo = nbPasCo;
        id_film = film;
        id_client = client;
        id_seance = seance;
    }

    //Sous méthode de conversion String to Date
    private Date toDate(String sdate) throws ParseException {
        Date date = new SimpleDateFormat("/MM/yyyy").parse(sdate);
        return date;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnValid = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        labelCrypto = new javax.swing.JLabel();
        labelNumCarte = new javax.swing.JLabel();
        Crypto = new javax.swing.JFormattedTextField();
        NumCarte = new javax.swing.JFormattedTextField();
        Nom = new javax.swing.JTextField();
        Date = new javax.swing.JFormattedTextField();
        DateExp = new javax.swing.JLabel();
        ImageFond = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(168, 26, 3));
        setBounds(new java.awt.Rectangle(600, 300, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(800, 400));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(null);

        btnValid.setBackground(new java.awt.Color(204, 204, 204));
        btnValid.setText("Valider");
        btnValid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnValidActionPerformed(evt);
            }
        });
        getContentPane().add(btnValid);
        btnValid.setBounds(350, 300, 80, 40);

        jLabel1.setText("  Nom sur la  carte");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(270, 70, 150, 15);

        labelCrypto.setText(" Cryptogramme");
        getContentPane().add(labelCrypto);
        labelCrypto.setBounds(450, 190, 80, 15);

        labelNumCarte.setText("Numéro de la carte");
        getContentPane().add(labelNumCarte);
        labelNumCarte.setBounds(270, 120, 200, 20);

        Crypto.setBackground(new java.awt.Color(204, 204, 204));
        try {
            Crypto.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(Crypto);
        Crypto.setBounds(450, 210, 80, 30);

        NumCarte.setBackground(new java.awt.Color(204, 204, 204));
        try {
            NumCarte.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("################")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(NumCarte);
        NumCarte.setBounds(270, 140, 260, 30);

        Nom.setBackground(new java.awt.Color(204, 204, 204));
        Nom.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NomMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                NomMouseExited(evt);
            }
        });
        getContentPane().add(Nom);
        Nom.setBounds(270, 90, 260, 30);

        Date.setBackground(new java.awt.Color(204, 204, 204));
        try {
            Date.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("## / ##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        Date.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Date.setToolTipText("");
        getContentPane().add(Date);
        Date.setBounds(270, 210, 60, 30);

        DateExp.setBackground(new java.awt.Color(0, 0, 0));
        DateExp.setText("Date d'expiration");
        getContentPane().add(DateExp);
        DateExp.setBounds(270, 190, 80, 15);

        ImageFond.setBackground(new java.awt.Color(168, 26, 3));
        ImageFond.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Background/pagepayement.png"))); // NOI18N
        getContentPane().add(ImageFond);
        ImageFond.setBounds(0, 0, 850, 480);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Suppression du text quand la souris clique
    private void NomMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NomMouseClicked
        Nom.setText(null);
    }//GEN-LAST:event_NomMouseClicked

    //On remet le text si la souris s'en va et que l'utilisateur n'a rien rempli
    private void NomMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NomMouseExited
        if (Nom.getText().equals("")) {
            Nom.setText("Nom sur la carte");
        }
    }//GEN-LAST:event_NomMouseExited

    //Action lors de la validation du payement
    private void btnValidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnValidActionPerformed
        //Initialisation du format de date et de la date actuelle
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("MM / yy");
        LocalDateTime now = LocalDateTime.now();

        //Verification que toutes les infos ont été rentré
        if ((NumCarte.getText().equals("Numero de la carte")) || (Nom.getText().equals("Nom sur la  carte")) || (Crypto.getText().equals("Cryptogramme")) || (Date.getText().equals("   /   "))) {
            JOptionPane.showMessageDialog(null, "Veuillez remplir tous les champs");
        } //Verification de la taille
        else if (NumCarte.getText().length() < 16) {
            JOptionPane.showMessageDialog(null, "Veuillez remplir tous les champs");
            NumCarte.setText(null);
            countNum = 0;
        } else if (Crypto.getText().length() < 3) {
            JOptionPane.showMessageDialog(null, "Veuillez remplir tous les champs");
            Crypto.setText(null);
            countCrypto = 0;
        } //verication de la validité
        else {
            try {
                //test pour voir si la carte est perimee
                if (!testDate(Date.getText())) {
                    JOptionPane.showMessageDialog(null, "Carte périmée");
                    Date.setText(null);
                } else {
                    JOptionPane.showMessageDialog(null, "Paiement Validé");
                    this.dispose();
                    try {
                        PayOK = true;
                        //Test si on a a faire a une personne connecte ou non
                        if (!connexionValid) {
                            //Recuperation des infos du billet
                            String Seance[];
                            String Film;
                            Seance = getSeance(id_seance);
                            Film = getFilm(id_film);

                            //Creation du billet
                            String billet = "Résumé Achat :\nNombre de place : " + nbVenduPasCo + "\nPrix total : " + 12 * nbVenduPasCo + "\nFilm : " + Film + "\nSeance du " + Seance[2] + " a " + Seance[1] + " en salle " + Seance[0];
                            String Nom = JOptionPane.showInputDialog(null, "Veuillez entrer le nom de la personne à qui appartient ce billet");
                            File fBillet = new File("C:\\Users\\pierr\\Documents\\Billet_" + Nom + ".txt");
                            if (!fBillet.exists()) {
                                try {
                                    fBillet.createNewFile();
                                } catch (IOException e) {
                                    e.printStackTrace();
                                }
                            }
                            try (PrintWriter print = new PrintWriter(new FileOutputStream(fBillet))) {
                                print.print(billet);
                            } catch (FileNotFoundException ex) {
                                Logger.getLogger(PagePayement.class.getName()).log(Level.SEVERE, null, ex);
                            }
                            JOptionPane.showMessageDialog(null, "Votre billet a été imprimé");
                            //La personne est connectee
                        } else {
                            //Ajout du billet dans la BDD
                            gestionBDD(nbVenduSernior, nbVenduMembre, nbVenduEnfant, nbVenduPasCo, id_client, id_film, id_seance);
                        }

                        //retour a la page d'accueil des lors que le billet est imprime
                        PageAccueil p = new PageAccueil(connexionValid, Emp);
                        p.setVisible(true);

                    } catch (SQLException ex) {
                        Logger.getLogger(PagePayement.class.getName()).log(Level.SEVERE, null, ex);
                    } catch (ClassNotFoundException ex) {
                        Logger.getLogger(PagePayement.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            } catch (ParseException ex) {
                Logger.getLogger(PagePayement.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnValidActionPerformed

    //Mise en place d'une fermeture propre de la fenetre en fonction de si le payement a ete ec=ffcetue ou pas
    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        if (!PayOK) {
            int result = JOptionPane.showConfirmDialog(null, "Voulez vous abandonner le payement ?", "Suppression", JOptionPane.YES_NO_OPTION);

            if (result == JOptionPane.YES_OPTION) {
                this.dispose();
                try {
                    PageSelecPrix psp = new PageSelecPrix(connexionValid, id_film, id_client, id_seance);
                    psp.setVisible(true);
                } catch (SQLException | ClassNotFoundException ex) {
                    Logger.getLogger(PagePayement.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else {
                PagePayement pp = new PagePayement(connexionValid, nbVenduMembre, nbVenduSernior, nbVenduEnfant, nbVenduPasCo, id_film, id_seance, id_client);
                pp.setVisible(true);
            }
        }
    }//GEN-LAST:event_formWindowClosing

    //Ajout des différents billets dans la BDD
    public void gestionBDD(int nbVenduSenior, int nbVenduMembre, int nbVenduEnfant, int nbVenduPasCo, int id_film, int id_client, int id_seance) throws SQLException, ClassNotFoundException {
        billet = new BilletDAO("cinema", "root", "");
        while (nbVenduSenior != 0) {
            billet.addBillet(8, id_client, id_seance, id_film, "Senior");
            nbVenduSenior--;
        }
        while (nbVenduMembre != 0) {
            billet.addBillet(10, id_client, id_seance, id_film, "Membre");
            nbVenduMembre--;
        }
        while (nbVenduEnfant != 0) {
            billet.addBillet(6, id_client, id_seance, id_film, "Enfant");
            nbVenduEnfant--;
        }
    }

    //Recuperation des infos d'une séance
    public String[] getSeance(int id_seance) throws SQLException, ClassNotFoundException {
        seance = new SeanceDAO("cinema", "root", "");
        String strSeance[] = {"", "", ""};
        DefaultListModel<String> Seance = new DefaultListModel<>();
        Seance = seance.getSeanceByID(id_seance);
        strSeance[0] = Seance.get(0);
        strSeance[2] = Seance.get(2);
        strSeance[1] = Seance.get(3);

        return strSeance;
    }

    //Recuperation du titre du film a partir de l'ID
    public String getFilm(int id_film) throws ClassNotFoundException, SQLException {
        film = new FilmDAO("cinema", "root", "");
        return (film.getFilmByID(Integer.toString(id_film))).get(0);
    }

    //Comparaison de date (sert pour la validite de la CB)
    public boolean testDate(String sDate) throws ParseException {
        SimpleDateFormat sdf = new SimpleDateFormat("MM / yy");
        boolean verif = false;
        Date dCarte = new Date();
        Date dAuj = new Date();
        dAuj = sdf.parse(sdf.format(new Date()));
        dCarte = sdf.parse(sDate);

        int result;
        result = dCarte.compareTo(dAuj);

        if (result < 0) {
            return verif;
        } else {
            return !verif;
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField Crypto;
    private javax.swing.JFormattedTextField Date;
    private javax.swing.JLabel DateExp;
    private javax.swing.JLabel ImageFond;
    private javax.swing.JTextField Nom;
    private javax.swing.JFormattedTextField NumCarte;
    private javax.swing.JButton btnValid;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel labelCrypto;
    private javax.swing.JLabel labelNumCarte;
    // End of variables declaration//GEN-END:variables
}
